services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      db:
        condition: service_healthy
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --no-access-log
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --no-access-log

  db:
    image: postgres:16
    container_name: app-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
