"""sortの追加

Revision ID: 2640a7d813bc
Revises: a17719029938
Create Date: 2026-08-17 07:31:17.383736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2640a7d813bc'
down_revision: Union[str, Sequence[str], None] = 'a17719029938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_accounting_basic_user_display_order'), 'accounting_basic', type_='unique')
    op.create_unique_constraint('uq_accounting_basic_user_sort', 'accounting_basic', ['user_id', 'sort'])
    op.drop_column('accounting_basic', 'display_order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_basic', sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_accounting_basic_user_sort', 'accounting_basic', type_='unique')
    op.create_unique_constraint(op.f('uq_accounting_basic_user_display_order'), 'accounting_basic', ['user_id', 'display_order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
