"""enumの修正

Revision ID: 2e6cc4c106bb
Revises: bf75b5172f84
Create Date: 2026-08-16 11:26:33.236810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e6cc4c106bb'
down_revision: Union[str, Sequence[str], None] = 'bf75b5172f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'power',
               existing_type=postgresql.ENUM('PRIME', 'GENERAL', name='power_type'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'power',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PRIME', 'GENERAL', name='power_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
