"""sortの追加

Revision ID: a17719029938
Revises: 2e6cc4c106bb
Create Date: 2026-08-17 07:24:45.605515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17719029938'
down_revision: Union[str, Sequence[str], None] = '2e6cc4c106bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounting_basic', sa.Column('sort', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounting_basic', 'sort')
    # ### end Alembic commands ###
